apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-processor
  namespace: default
spec:
  replicas: 0
  selector:
    matchLabels:
      app: log-processor
  template:
    metadata:
      labels:
        app: log-processor
    spec:
      serviceAccountName: response-engine-sa
      containers:
        - name: log-processor
          image: acrfypfyp.azurecr.io/log-processor:latest
          env:
            - name: SERVICEBUS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: servicebus-secret
                  key: connection-string
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi