apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: servicebus-triggerauth
  namespace: default
spec:
  secretTargetRef:
    - parameter: connection
      name: servicebus-secret
      key: connection-string

---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: log-processor-scaler
  namespace: default
spec:
  scaleTargetRef:
    name: log-processor
  minReplicaCount: 0
  maxReplicaCount: 10
  cooldownPeriod: 10
  triggers:
    - type: azure-servicebus
      metadata:
        queueName: log-queue
        namespace: sb-fyp-logs
        messageCount: "5"
      authenticationRef:
        name: servicebus-triggerauth